# ===== BUILD =====
FROM node:20-alpine AS builder

WORKDIR /app

COPY api-gateway/package*.json ./
RUN npm ci

COPY api-gateway ./
# File từ máy thật copy vào /app/proto-contracts trong container
COPY proto-contracts ./proto-contracts

RUN npm run build
RUN npm prune --omit=dev

# ===== RUNTIME =====
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# SỬA TẠI ĐÂY: Thêm /app vào trước proto-contracts
COPY --from=builder /app/proto-contracts ./proto-contracts

CMD ["node", "dist/main.js"]