# ===== BUILD =====
FROM node:20-alpine AS builder

WORKDIR /app

COPY auth-service/package*.json ./
RUN npm ci

COPY auth-service ./
COPY proto-contracts ./proto-contracts
COPY auth-service/prisma ./prisma

RUN npm run build

# check build output (debug cực quan trọng)
RUN ls -la dist

RUN npm prune --omit=dev


# ===== RUNTIME =====
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/main.js"]